# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

#  fileSystems."/" =
#    { device = "/dev/disk/by-uuid/28b37391-4ee6-4369-9db5-de4afd0d4b60";
#      fsType = "btrfs";
#      options = [ "subvol=@" ];
#    };

#  fileSystems."/home" =
#    { device = "/dev/disk/by-uuid/28b37391-4ee6-4369-9db5-de4afd0d4b60";
#      fsType = "btrfs";
#      options = [ "subvol=@home" ];
#    };

#  fileSystems."/nix" =
#    { device = "/dev/disk/by-uuid/28b37391-4ee6-4369-9db5-de4afd0d4b60";
#      fsType = "btrfs";
#      options = [ "subvol=@nix" ];
#    };

#  fileSystems."/swap" =
#    { device = "/dev/disk/by-uuid/28b37391-4ee6-4369-9db5-de4afd0d4b60";
#      fsType = "btrfs";
#      options = [ "subvol=@swap" ];
#    };

#  fileSystems."/boot" =
#    { device = "/dev/disk/by-uuid/28b37391-4ee6-4369-9db5-de4afd0d4b60";
#      fsType = "btrfs";
#    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
