version: "3.8"

services:
  pihole:
    image: "pihole/pihole:latest"
    container_name: "pihole"
    restart: unless-stopped
    ports:
      - "53:53/tcp"   # DNS port (TCP) - available to network
      - "53:53/udp"   # DNS port (UDP) - available to network
      - "80:80/tcp"   # Web interface (HTTP)
      - "443:443/tcp" # Web interface (HTTPS)
    volumes:
      - "pihole_data:/etc/pihole"
      - "dnsmasq_data:/etc/dnsmasq.d"
    environment:
      - TZ=Europe/London
      - WEBPASSWORD="${PIHOLE_PASSWORD}"
      - DNS1=1.1.1.1
      - DNS2=8.8.8.8
      - SERVERIP=192.168.1.63
      - DNSMASQ_USER=root
      - DNSMASQ_LISTENING=all
    extra_hosts:
      - "pihole:${SERVERIP}"
    cap_add:
      - "NET_ADMIN"
    networks:
      - pihole_network
    env_file:
      - .env

volumes:
  pihole_data:
  dnsmasq_data:

networks:
  pihole_network:
    driver: bridge
