# Pihole on nixos-pi
version: "3.8"

services:
  pihole:
    image: "pihole/pihole:latest"
    container_name: "pihole"
    restart: unless-stopped
    ports:
      - "53:53/tcp"   # DNS port (TCP) - available to network
      - "53:53/udp"   # DNS port (UDP) - available to network
      - "80:80/tcp"   # Web interface (HTTP)
      - "443:443/tcp" # Web interface (HTTPS)
    volumes:
      - "/home/nixos/containers/pihole/pihole:/etc/pihole"
      - "/home/nixos/containers/pihole/dnsmasq.d:/etc/dnsmasq.d"
    environment:
      - TZ=Europe/London
      - WEBPASSWORD="${PIHOLE_PASSWORD}"  # Assuming you set this in an .env file or other way
      - DNS1=1.1.1.1
      - DNS2=8.8.8.8
      - SERVERIP=192.168.1.63  # Pi's IP addresscd 
      - DNSMASQ_USER=root
      - DNSMASQ_LISTENING=all  # This will listen on all interfaces including VPN subnets
    extra_hosts:
      - "pihole:${SERVERIP}"
    cap_add:
      - "NET_ADMIN"  # Required for network-related operations
    networks:
      - pihole_network

networks:
  pihole_network:
    driver: bridge